"""add release_form table

Revision ID: 1f5a153469b4
Revises: 7ec4b356fdb1
Create Date: 2024-11-02 10:09:17.214758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f5a153469b4"
down_revision: Union[str, None] = "7ec4b356fdb1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_forms",
        sa.Column("primary_packaging", sa.String(length=255), nullable=False),
        sa.Column("count_primary_packaging", sa.Integer(), nullable=False),
        sa.Column("gtin", sa.String(length=255), nullable=False),
        sa.Column("id_drug_name", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("registration_certificate_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["registration_certificate_id"],
            ["registration_certificates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "registration_certificates",
        "is_Active",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "registration_certificates",
        "is_Active",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.drop_table("release_forms")
    # ### end Alembic commands ###
