"""create new tables

Revision ID: 2587ceb0dcd2
Revises: 
Create Date: 2025-02-12 12:30:06.889955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2587ceb0dcd2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_certificates",
        sa.Column("trade_Name", sa.String(), nullable=False),
        sa.Column("reg_Cert_Number", sa.String(), nullable=False),
        sa.Column("createAt_Reg_Cer", sa.DateTime(), nullable=False),
        sa.Column("is_Active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reg_Cert_Number"),
    )
    op.create_table(
        "release_forms",
        sa.Column("primary_packaging", sa.String(length=255), nullable=False),
        sa.Column("count_primary_packaging", sa.Integer(), nullable=False),
        sa.Column("gtin", sa.String(length=255), nullable=False),
        sa.Column("id_drug_name", sa.String(length=255), nullable=False),
        sa.Column("registration_certificate_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["registration_certificate_id"],
            ["registration_certificates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_forms")
    op.drop_table("registration_certificates")
    # ### end Alembic commands ###
